# Generated by Django 4.2.13 on 2024-07-25 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookResources',
            fields=[
                ('ebooksID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
                ('teacherName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('ClassID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('GradeID', models.AutoField(primary_key=True, serialize=False)),
                ('GradeValue', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.AutoField(primary_key=True, serialize=False)),
                ('TeacherName', models.CharField(max_length=100, unique=True)),
                ('TeacherEmail', models.EmailField(max_length=100, unique=True)),
                ('TeacherPassword', models.CharField(max_length=50)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=100, unique=True)),
                ('GradeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=100, unique=True)),
                ('StudentEmail', models.EmailField(max_length=100, unique=True)),
                ('StudentPassword', models.CharField(max_length=50)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('NotificationID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('EnrollmentID', models.AutoField(primary_key=True, serialize=False)),
                ('EnrollmentDate', models.DateField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classes')),
                ('GradeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.grade')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='ClassStudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='classes',
            name='ClassTeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
