# Generated by Django 4.2.13 on 2024-07-25 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyResourse',
            fields=[
                ('studyResourseId', models.AutoField(primary_key=True, serialize=False)),
                ('resourceInfo', models.CharField(max_length=255)),
                ('resource', models.FileField(upload_to='course_resources/')),
                ('subjecttId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subject')),
            ],
        ),
    ]
