# Generated by Django 5.0 on 2024-05-25 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('ClassID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('GradeID', models.AutoField(primary_key=True, serialize=False)),
                ('GradeValue', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=100, unique=True)),
                ('StudentEmail', models.EmailField(max_length=100, unique=True)),
                ('StudentPassword', models.CharField(max_length=50)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('EnrollmentID', models.AutoField(primary_key=True, serialize=False)),
                ('EnrollmentDate', models.DateField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classes')),
                ('GradeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.grade')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='ClassStudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=100, unique=True)),
                ('SubjectDescription', models.CharField(max_length=100)),
                ('GradeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Physics',
            fields=[
                ('PhysicsID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100)),
                ('File', models.FileField(upload_to='physics/')),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.AutoField(primary_key=True, serialize=False)),
                ('TeacherName', models.CharField(max_length=100, unique=True)),
                ('TeacherEmail', models.EmailField(max_length=100, unique=True)),
                ('TeacherPassword', models.CharField(max_length=50)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='ClassTeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
