# Generated by Django 4.2.13 on 2024-07-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='NotifierID',
            field=models.IntegerField(default=2),
        ),
    ]
