# Generated by Django 4.2.13 on 2024-08-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_course_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.grade'),
        ),
    ]
