# Generated by Django 4.2.13 on 2024-07-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studyresourse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyResourse',
            new_name='StudyResource',
        ),
    ]
