# Generated by Django 5.0 on 2024-05-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_classes_grade_student_enrollment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='SubjectDescription',
        ),
    ]
