# Generated by Django 5.0 on 2024-05-26 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_subject_subjectdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('NotificationID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
