# Generated by Django 4.2.13 on 2024-07-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notifications_notifierid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='TeacherID',
        ),
    ]
