# Generated by Django 4.2.13 on 2024-07-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_studyresourse_studyresource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyresource',
            old_name='studyResourseId',
            new_name='studyResourceId',
        ),
        migrations.RenameField(
            model_name='studyresource',
            old_name='subjecttId',
            new_name='subjectID',
        ),
    ]
