# Generated by Django 4.2.13 on 2024-08-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teacher_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Term', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='reportcard',
            old_name='reportCardID',
            new_name='report_id',
        ),
        migrations.AddField(
            model_name='reportcard',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.grade'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.subject'),
        ),
    ]
