# Generated by Django 4.2.13 on 2024-07-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookResources',
            fields=[
                ('ebooksID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
                ('teacherName', models.CharField(max_length=255)),
            ],
        ),
    ]
