# Generated by Django 4.2.13 on 2024-08-06 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_term_rename_reportcardid_reportcard_report_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.term'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='subject',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
