# Generated by Django 4.2.13 on 2024-07-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_notifications_notifierid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='Role',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
