# Generated by Django 4.2.13 on 2024-08-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_reportcard_marks_reportcard_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subject'),
        ),
    ]
