# Generated by Django 4.2.13 on 2024-08-06 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_reportcard_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.subject'),
        ),
    ]
